### ISSUE TITLE
Changes to source will not rerender canvas. Scope watch need to be added.

### ISSUE THREAD

**Issue by ghost** [aztech-digital/angular-thumbnails#1]
This:

```
        if (renderer) {
          renderer.render();
        }
```

needs to be changed to this:

```
        scope.$watch("source", function(newValue, oldValue){
          if (renderer) {
            renderer.render();
          }
        });
```

**Comment by fabre-thibaud** [comment]
Hello,

Thanks for your suggestion ! I've updated the library to watch on all thumbnail properties so that any change will trigger re-rendering.

I'm closing this issue, feel free to re-open as needed.
