### ISSUE TITLE
Problem with minification

### ISSUE THREAD

**Issue by mebibou** [aztech-digital/angular-thumbnails#6]
Could you remove the `$window` on this line: https://github.com/aztech-digital/angular-thumbnails/blob/master/src/angular-thumbnails.js#L168 ?

You are actually not using it, and when using Webpack and minification it will create a nasty error:
```
Error: [$injector:unpr] Unknown provider: iProvider <- i <- thumbnailDirective
```

If you actually use the provider, you should write it like this:
```
angular.module('angular-thumbnails', []).directive('thumbnail', ['$window', function ($window) {
```

Thanks

**Comment by fabre-thibaud** [comment]
Thanks for fixing the issue. Your PR is released as 0.2.3.

Sorry I didn't get around to fixing this earlier
